/**
 * Synaps IndividualLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for DocumentType1Enum
 */
export enum DocumentType1Enum {
  ELECTRICITYBILL = 'ELECTRICITY_BILL',
  GASBILL = 'GAS_BILL',
  LANDLINEBILL = 'LANDLINE_BILL',
  WATERBILL = 'WATER_BILL',
  INTERNETBILL = 'INTERNET_BILL',
  BANKSTATEMENT = 'BANK_STATEMENT',
}

/**
 * Schema for DocumentType1Enum
 */
export const documentType1EnumSchema: Schema<DocumentType1Enum> = stringEnum(DocumentType1Enum);
