/**
 * Synaps IndividualLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for FiletypeEnum
 */
export enum FiletypeEnum {
  EnumApplicationpdf = 'application/pdf',
  EnumImagejpeg = 'image/jpeg',
  EnumImagepng = 'image/png',
}

/**
 * Schema for FiletypeEnum
 */
export const filetypeEnumSchema: Schema<FiletypeEnum> = stringEnum(FiletypeEnum);
