/**
 * Synaps IndividualLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { IdentityDocument, identityDocumentSchema } from './identityDocument';
import {
  IdentityDocumentDetails,
  identityDocumentDetailsSchema,
} from './identityDocumentDetails';
import { StateEnum, stateEnumSchema } from './stateEnum';

export interface IdentityVerificationDocument {
  document?: IdentityDocument;
  state?: StateEnum;
  details?: IdentityDocumentDetails;
}

export const identityVerificationDocumentSchema: Schema<IdentityVerificationDocument> = object(
  {
    document: ['document', optional(lazy(() => identityDocumentSchema))],
    state: ['state', optional(stateEnumSchema)],
    details: ['details', optional(lazy(() => identityDocumentDetailsSchema))],
  }
);
