/**
 * Synaps IndividualLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import { State1Enum, state1EnumSchema } from './state1Enum';

export interface IdentityDuplicate {
  /** Verification state */
  state?: State1Enum;
}

export const identityDuplicateSchema: Schema<IdentityDuplicate> = object({
  state: ['state', optional(state1EnumSchema)],
});
