/**
 * Synaps IndividualLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema, string } from '../schema';

export interface IdentityFeatures {
  /** name of the feature */
  name?: string;
  /** feature unique identifier */
  slug?: string;
  /** document side where the feature is FRONT / BACK */
  documentSlide?: string;
  /** If the feature is included */
  included?: boolean;
}

export const identityFeaturesSchema: Schema<IdentityFeatures> = object({
  name: ['name', optional(string())],
  slug: ['slug', optional(string())],
  documentSlide: ['document_slide', optional(string())],
  included: ['included', optional(boolean())],
});
