/**
 * Synaps IndividualLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import { State1Enum, state1EnumSchema } from './state1Enum';

export interface IdentityHistory {
  userReason?: string;
  customerReason?: string;
  rejectionCode?: string;
  submittedAt?: string;
  verifiedAt?: string;
  /** Verification state */
  state?: State1Enum;
}

export const identityHistorySchema: Schema<IdentityHistory> = object({
  userReason: ['user_reason', optional(string())],
  customerReason: ['customer_reason', optional(string())],
  rejectionCode: ['rejection_code', optional(string())],
  submittedAt: ['submitted_at', optional(string())],
  verifiedAt: ['verified_at', optional(string())],
  state: ['state', optional(state1EnumSchema)],
});
