/**
 * Synaps IndividualLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import { TypeEnum, typeEnumSchema } from './typeEnum';

export interface IdentityDocument {
  type?: TypeEnum;
  /** Issuing country (code ISO-3166) */
  country?: string;
  /** image of the front document available through a signed URL (15 minutes expiry) */
  frontFile?: string;
  /** image of the back document available through a signed URL (15 minutes expiry) */
  backFile?: string;
}

export const identityDocumentSchema: Schema<IdentityDocument> = object({
  type: ['type', optional(typeEnumSchema)],
  country: ['country', optional(string())],
  frontFile: ['front_file', optional(string())],
  backFile: ['back_file', optional(string())],
});
