/**
 * Synaps IndividualLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema, string } from '../schema';

export interface IdentityInfo {
  /** name of the field */
  name?: string;
  /** document side where the info is FRONT / BACK */
  documentSide?: string;
  /** unique info identifier */
  slug?: string;
  /** crosscheckable if there is a MRZ with a value to crosscheck */
  crossCheckable?: boolean;
  /** crosschecked with MRZ if any */
  crossChecked?: boolean;
  /** value of the info */
  value?: string;
}

export const identityInfoSchema: Schema<IdentityInfo> = object({
  name: ['name', optional(string())],
  documentSide: ['document_side', optional(string())],
  slug: ['slug', optional(string())],
  crossCheckable: ['cross_checkable', optional(boolean())],
  crossChecked: ['cross_checked', optional(boolean())],
  value: ['value', optional(string())],
});
