/**
 * Synaps IndividualLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { IdentityInfo, identityInfoSchema } from './identityInfo';

export interface IdentityDocumentInfo {
  firstname?: IdentityInfo;
  lastname?: IdentityInfo;
  birthDate?: IdentityInfo;
  documentExpiration?: IdentityInfo;
  documentNumber?: IdentityInfo;
}

export const identityDocumentInfoSchema: Schema<IdentityDocumentInfo> = object({
  firstname: ['firstname', optional(lazy(() => identityInfoSchema))],
  lastname: ['lastname', optional(lazy(() => identityInfoSchema))],
  birthDate: ['birth_date', optional(lazy(() => identityInfoSchema))],
  documentExpiration: [
    'document_expiration',
    optional(lazy(() => identityInfoSchema)),
  ],
  documentNumber: ['document_number', optional(lazy(() => identityInfoSchema))],
});
