/**
 * Synaps IndividualLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  IdentityDocumentFeatures,
  identityDocumentFeaturesSchema,
} from './identityDocumentFeatures';
import {
  IdentityDocumentInfo,
  identityDocumentInfoSchema,
} from './identityDocumentInfo';
import {
  IdentityDocumentMrz,
  identityDocumentMrzSchema,
} from './identityDocumentMrz';

export interface IdentityDocumentDetails {
  info?: IdentityDocumentInfo;
  features?: IdentityDocumentFeatures;
  mrz?: IdentityDocumentMrz;
}

export const identityDocumentDetailsSchema: Schema<IdentityDocumentDetails> = object(
  {
    info: ['info', optional(lazy(() => identityDocumentInfoSchema))],
    features: [
      'features',
      optional(lazy(() => identityDocumentFeaturesSchema)),
    ],
    mrz: ['mrz', optional(lazy(() => identityDocumentMrzSchema))],
  }
);
