/**
 * Synaps IndividualLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { IdentityFeatures, identityFeaturesSchema } from './identityFeatures';

export interface IdentityDocumentFeatures {
  /** list of document fields */
  security?: IdentityFeatures[];
  /** list of document fields */
  fields?: IdentityFeatures[];
}

export const identityDocumentFeaturesSchema: Schema<IdentityDocumentFeatures> = object(
  {
    security: ['security', optional(array(lazy(() => identityFeaturesSchema)))],
    fields: ['fields', optional(array(lazy(() => identityFeaturesSchema)))],
  }
);
