/**
 * Synaps IndividualLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema, string } from '../schema';

export interface IdentityMrz {
  /** Name of the MRZ field */
  name?: string;
  /** document side where the feature is FRONT / BACK */
  documentSlide?: string;
  /** unique identifier */
  slug?: string;
  /** true if MRZ algorithm is verified false if MRZ algorithm is not verified */
  valid?: boolean;
}

export const identityMrzSchema: Schema<IdentityMrz> = object({
  name: ['name', optional(string())],
  documentSlide: ['document_slide', optional(string())],
  slug: ['slug', optional(string())],
  valid: ['valid', optional(boolean())],
});
