/**
 * Synaps IndividualLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { IdentityMrz, identityMrzSchema } from './identityMrz';

export interface IdentityDocumentMrz {
  lines?: IdentityMrz;
  barcode?: IdentityMrz;
}

export const identityDocumentMrzSchema: Schema<IdentityDocumentMrz> = object({
  lines: ['lines', optional(lazy(() => identityMrzSchema))],
  barcode: ['barcode', optional(lazy(() => identityMrzSchema))],
});
