/**
 * Synaps IndividualLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';
import { State1Enum, state1EnumSchema } from './state1Enum';

export interface LivenessVerificationResponse {
  /** number of liveness attempts */
  attempts?: number;
  /** Successful enrollment date Datetime format : YYYY-MM-DD hh:ii:ss */
  enrollmentDate?: string;
  /** image of the user's face available through a signed URL (15 minutes expiry) */
  face?: string;
  /** Verification state */
  state?: State1Enum;
}

export const livenessVerificationResponseSchema: Schema<LivenessVerificationResponse> = object(
  {
    attempts: ['attempts', optional(number())],
    enrollmentDate: ['enrollment_date', optional(string())],
    face: ['face', optional(string())],
    state: ['state', optional(state1EnumSchema)],
  }
);
