/**
 * Synaps IndividualLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface LivenessInitResponse {
  /** Liveness challenge unique token */
  token?: string;
}

export const livenessInitResponseSchema: Schema<LivenessInitResponse> = object({
  token: ['token', optional(string())],
});
