/**
 * Synaps IndividualLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema, string } from '../schema';

export interface LivenessVerifyResponse {
  /** true if challenge is passed false if challenge is failed */
  success?: boolean;
  /** empty if success is true Failure reason challenge failed */
  reason?: string;
}

export const livenessVerifyResponseSchema: Schema<LivenessVerifyResponse> = object(
  {
    success: ['success', optional(boolean())],
    reason: ['reason', optional(string())],
  }
);
