/**
 * Synaps IndividualLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for MethodEnum
 */
export enum MethodEnum {
  Sms = 'sms',
  Call = 'call',
}

/**
 * Schema for MethodEnum
 */
export const methodEnumSchema: Schema<MethodEnum> = stringEnum(MethodEnum);
