/**
 * Synaps IndividualLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for MethodeEnum
 */
export enum MethodeEnum {
  Sms = 'sms',
  Call = 'call',
}

/**
 * Schema for MethodeEnum
 */
export const methodeEnumSchema: Schema<MethodeEnum> = stringEnum(MethodeEnum);
