/**
 * Synaps IndividualLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import { MethodeEnum, methodeEnumSchema } from './methodeEnum';

export interface PhoneVerificationAttempt {
  /** attempt date (YYYY-MM-DD HH:ii:ss) */
  date?: string;
  methode?: MethodeEnum;
}

export const phoneVerificationAttemptSchema: Schema<PhoneVerificationAttempt> = object(
  {
    date: ['date', optional(string())],
    methode: ['methode', optional(methodeEnumSchema)],
  }
);
