/**
 * Synaps IndividualLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface PhoneVerificationCarrier {
  /** country calling code */
  phoneCountry?: string;
  /** phone number */
  phoneNumber?: string;
}

export const phoneVerificationCarrierSchema: Schema<PhoneVerificationCarrier> = object(
  {
    phoneCountry: ['phone_country', optional(string())],
    phoneNumber: ['phone_number', optional(string())],
  }
);
