/**
 * Synaps IndividualLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { ResidencyHistory, residencyHistorySchema } from './residencyHistory';
import {
  ResidencyVerificationDocument,
  residencyVerificationDocumentSchema,
} from './residencyVerificationDocument';
import { State1Enum, state1EnumSchema } from './state1Enum';

export interface ResidencyVerificationResponse {
  document?: ResidencyVerificationDocument;
  history?: ResidencyHistory[];
  /** Verification state */
  state?: State1Enum;
}

export const residencyVerificationResponseSchema: Schema<ResidencyVerificationResponse> = object(
  {
    document: [
      'document',
      optional(lazy(() => residencyVerificationDocumentSchema)),
    ],
    history: ['history', optional(array(lazy(() => residencyHistorySchema)))],
    state: ['state', optional(state1EnumSchema)],
  }
);
