/**
 * Synaps IndividualLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface ResidencyInfo {
  /** User firstname */
  firstname?: string;
  /** User lastname */
  lastname?: string;
  /** Postal address */
  address?: string;
  /** Country of residence */
  country?: string;
  /** City of residence */
  city?: string;
  /** Zip Code (might be empty) */
  zipcode?: string;
  /** Date format YYYY-MM-DD */
  issuingDate?: string;
}

export const residencyInfoSchema: Schema<ResidencyInfo> = object({
  firstname: ['firstname', optional(string())],
  lastname: ['lastname', optional(string())],
  address: ['address', optional(string())],
  country: ['country', optional(string())],
  city: ['city', optional(string())],
  zipcode: ['zipcode', optional(string())],
  issuingDate: ['issuing_date', optional(string())],
});
