/**
 * Synaps IndividualLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import { State1Enum, state1EnumSchema } from './state1Enum';

export interface ResidencyHistory {
  /** User reason is a reason that you should display to your end-user */
  userReason?: string;
  /** Customer reason is an internal reason and it should not be displayed to your end-user */
  customeReason?: string;
  /** Synaps rejection code */
  rejectionCode?: string;
  /** Datetime format YYYY-MM-DD hh:ii:ss */
  submittedAt?: string;
  /** Datetime format YYYY-MM-DD hh:ii:ss */
  verifiedAt?: string;
  /** Verification state */
  state?: State1Enum;
}

export const residencyHistorySchema: Schema<ResidencyHistory> = object({
  userReason: ['user_reason', optional(string())],
  customeReason: ['custome_reason', optional(string())],
  rejectionCode: ['rejection_code', optional(string())],
  submittedAt: ['submitted_at', optional(string())],
  verifiedAt: ['verified_at', optional(string())],
  state: ['state', optional(state1EnumSchema)],
});
