/**
 * Synaps IndividualLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import { FiletypeEnum, filetypeEnumSchema } from './filetypeEnum';
import { Type1Enum, type1EnumSchema } from './type1Enum';

export interface ResidencyDocument {
  type?: Type1Enum;
  filetype?: FiletypeEnum;
  /** image of the document available through a signed URL (15 minutes expiry) */
  file?: string;
}

export const residencyDocumentSchema: Schema<ResidencyDocument> = object({
  type: ['type', optional(type1EnumSchema)],
  filetype: ['filetype', optional(filetypeEnumSchema)],
  file: ['file', optional(string())],
});
