/**
 * Synaps IndividualLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import { StatusEnum, statusEnumSchema } from './statusEnum';

export interface SessionAlias {
  sessionId?: string;
  alias?: string;
  status?: StatusEnum;
}

export const sessionAliasSchema: Schema<SessionAlias> = object({
  sessionId: ['session_id', optional(string())],
  alias: ['alias', optional(string())],
  status: ['status', optional(statusEnumSchema)],
});
