/**
 * Synaps IndividualLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema, string } from '../schema';
import { StatusEnum, statusEnumSchema } from './statusEnum';

export interface SessionInfo {
  sessionId?: string;
  alias?: string;
  status?: StatusEnum;
  sandbox?: boolean;
}

export const sessionInfoSchema: Schema<SessionInfo> = object({
  sessionId: ['session_id', optional(string())],
  alias: ['alias', optional(string())],
  status: ['status', optional(statusEnumSchema)],
  sandbox: ['sandbox', optional(boolean())],
});
