/**
 * Synaps IndividualLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema, string } from '../schema';

export interface SessionCreated {
  /** Session-Id just created */
  sessionId?: string;
  /** true if the session is a sandbox session, false if the session is a normal session */
  sandbox?: boolean;
}

export const sessionCreatedSchema: Schema<SessionCreated> = object({
  sessionId: ['session_id', optional(string())],
  sandbox: ['sandbox', optional(boolean())],
});
