/**
 * Synaps IndividualLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for State10Enum
 */
export enum State10Enum {
  PENDING = 'PENDING',
  VERIFIED = 'VERIFIED',
  CANCELLED = 'CANCELLED',
}

/**
 * Schema for State10Enum
 */
export const state10EnumSchema: Schema<State10Enum> = stringEnum(State10Enum);
