/**
 * Synaps IndividualLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for TypeEnum
 */
export enum TypeEnum {
  NATIONALID = 'NATIONAL_ID',
  PASSPORT = 'PASSPORT',
  DRIVERLICENSE = 'DRIVER_LICENSE',
  RESIDENTPERMIT = 'RESIDENT_PERMIT',
}

/**
 * Schema for TypeEnum
 */
export const typeEnumSchema: Schema<TypeEnum> = stringEnum(TypeEnum);
